apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-study-chat-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: backend-study-chat
  template:
    metadata:
      labels:
        app: backend-study-chat
    spec:
      containers:
        - name: backend-study-chat
          image: jae0ne/studyhub-study-chat:0.0.1
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: backend-chat-mysql-secret
                  key: MYSQL_DB_USERNAME
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: backend-chat-mysql-secret
                  key: MYSQL_DB_PASSWORD
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /etc/config
              name: backend-chat-config-volume
              readOnly: true
            - mountPath: /etc/kafka
              name: backend-kafka-secret-volume
              readOnly: true
      volumes:
        - name: backend-chat-config-volume
          configMap:
            name: backend-chat-config
            items:
              - key: application-dev.yml
                path: application-dev.yml
        - name: backend-kafka-secret-volume
          secret:
            secretName: backend-kafka-secret-volume
            items:
              - key: kafka.yaml
                path: application-dev-kafka.yml
