apiVersion: v1
kind: Service
metadata:
  name: backend-study-chat-nodeport
spec:
  type: NodePort
  selector:
    app: backend-study-chat
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30081
  sessionAffinity: ClientIP
