apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-study-chat-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: backend-study-chat
  template:
    metadata:
      labels:
        app: backend-study-chat
    spec:
      containers:
        - name: backend-study-chat
          image: jae0ne/studyhub-study-chat:0.1.8
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /etc/config
              name: chat-configmap
              readOnly: true
            - mountPath: /etc/mysql
              name: mysql-jdbc-secret
              readOnly: true
            - mountPath: /etc/kafka
              name: kafka-secret
              readOnly: true
      volumes:
        - name: chat-configmap
          configMap:
            name: chat-configmap
            items:
              - key: application-dev.yml
                path: application-dev.yml
        - name: mysql-jdbc-secret
          secret:
            secretName: mysql-jdbc-secret-volume
            items:
              - key: application-mysql.yml
                path: application-mysql.yml
        - name: kafka-secret
          secret:
            secretName: kafka-secret-volume
            items:
              - key: kafka.yaml
                path: application-kafka.yml
